project_name: nina
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
nfpms:
- maintainer: Niklas Johansson <raphexion@gmail.com>
  description: CLI to interact with Noko time tracking.
  homepage: https://github.com/Raphexion/nina
  license: Apache License Version 2.0
  formats:
  - deb
  - rpm
  - apk
